"use client";

import { ArrowRight, Bot, Check, CircleHelp, Clock3, Eye, Filter, Newspaper, Pause, PawPrint, Play, Radio, Search, Sparkles, Sprout } from "lucide-react";
import { useState } from "react";
import type { CyberLessonComponentProps } from "../../lesson-types";
import { PracticeShell, usePractice } from "./PracticeShell";
import s from "./practice.module.css";
import m from "./worlds.module.css";

type Props = CyberLessonComponentProps;
type Kind = "Alive" | "Machine";
const livingTasks: { prompt: string; items: { name: string; kind: Kind; icon: "paw" | "plant" | "bot" | "radio" | "clock" }[] }[] = [
  { prompt: "Sort the objects in Cyberpur's classroom.", items: [{ name: "Puppy", kind: "Alive", icon: "paw" }, { name: "Smart speaker", kind: "Machine", icon: "radio" }, { name: "Dancing robot", kind: "Machine", icon: "bot" }] },
  { prompt: "The clock can move. Does that make it alive?", items: [{ name: "Sunflower", kind: "Alive", icon: "plant" }, { name: "Classroom clock", kind: "Machine", icon: "clock" }, { name: "Puppy", kind: "Alive", icon: "paw" }] },
  { prompt: "Try a new group, including a machine that talks.", items: [{ name: "Talking toy", kind: "Machine", icon: "bot" }, { name: "Seedling", kind: "Alive", icon: "plant" }, { name: "Smart speaker", kind: "Machine", icon: "radio" }] },
];
function ObjectIcon({ icon }: { icon: (typeof livingTasks)[number]["items"][number]["icon"] }) { return icon === "paw" ? <PawPrint aria-hidden="true" /> : icon === "plant" ? <Sprout aria-hidden="true" /> : icon === "clock" ? <Clock3 aria-hidden="true" /> : icon === "radio" ? <Radio aria-hidden="true" /> : <Bot aria-hidden="true" />; }
function LivingSorter({ task, submit }: { task: (typeof livingTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [active, setActive] = useState(""); const [placed, setPlaced] = useState<Record<string, Kind>>({});
  return <div className={m.panel}><div className={m.tileGrid}>{task.items.map((item) => <button aria-pressed={active === item.name} className={m.objectTile} key={item.name} onClick={() => setActive(item.name)} type="button"><ObjectIcon icon={item.icon} /><strong>{item.name}</strong><small>{placed[item.name] ?? "Tap to sort"}</small></button>)}</div><div className={m.bags}>{(["Alive", "Machine"] as Kind[]).map((kind) => <button className={m.bag} disabled={!active} key={kind} onClick={() => { setPlaced((current) => ({ ...current, [active]: kind })); setActive(""); }} type="button">{kind === "Alive" ? <Sprout aria-hidden="true" /> : <Bot aria-hidden="true" />}<strong>{kind}</strong><small>{kind === "Alive" ? "Grows and needs care" : "Follows a program"}</small></button>)}</div><button className={s.primary} disabled={task.items.some((item) => !placed[item.name])} onClick={() => { const wrong = task.items.find((item) => placed[item.name] !== item.kind); submit(!wrong, wrong ? `${wrong.name}: moving or talking does not prove something is alive. Try its other station.` : "All sorted. Living things grow and need care; machines follow instructions."); }} type="button"><Check aria-hidden="true" /> Check sorting stations</button></div>;
}
export function RobotOrNot(props: Props) { const p = usePractice(props); const task = livingTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Living or programmed" brief="A machine may move or speak, but it follows instructions. Living things grow and need care." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="ai"><LivingSorter key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

type Label = "Fruit" | "Not fruit";
const petTasks = [
  { prompt: "Teach the pet: label an apple and a rock.", samples: [{ name: "Red apple", kind: "Fruit" as Label, glyph: "🍎" }, { name: "Grey rock", kind: "Not fruit" as Label, glyph: "🪨" }], test: "Red apple", result: "The sorter learned from two examples." },
  { prompt: "It calls an orange 'unknown'. Add a different fruit example.", samples: [{ name: "Orange", kind: "Fruit" as Label, glyph: "🍊" }, { name: "Round pebble", kind: "Not fruit" as Label, glyph: "🪨" }], test: "Orange", result: "Adding orange widened the pet's fruit examples." },
  { prompt: "Transfer the lesson to two new objects.", samples: [{ name: "Banana", kind: "Fruit" as Label, glyph: "🍌" }, { name: "Toy ball", kind: "Not fruit" as Label, glyph: "⚽" }], test: "Banana", result: "A wider set helps, but a real model would need many more examples." },
];
function PetTrainer({ task, submit }: { task: (typeof petTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [active, setActive] = useState(""); const [labels, setLabels] = useState<Record<string, Label>>({}); const [ran, setRan] = useState(false);
  return <div className={m.duo}><div className={m.petMachine}><Bot aria-hidden="true" /><strong>PET SORTER</strong><span>{ran ? `TEST: ${task.test} → ${labels[task.test] ?? "Unknown"}` : "Waiting for examples"}</span><div className={m.machineEyes}><i /><i /></div><div className={m.conveyor}>{task.samples.map((item) => <button aria-pressed={active === item.name} className={m.sample} key={item.name} onClick={() => setActive(item.name)} type="button"><span>{item.glyph}</span><small>{item.name}</small><b>{labels[item.name] ?? "?"}</b></button>)}</div></div><div className={m.panel}><h3>Feed labelled examples</h3><p>Tap a sample, then give the pet its label. Test what it learned.</p><div className={m.bags}>{(["Fruit", "Not fruit"] as Label[]).map((label) => <button className={m.bag} disabled={!active} key={label} onClick={() => { setLabels((current) => ({ ...current, [active]: label })); setActive(""); setRan(false); }} type="button"><Sparkles aria-hidden="true" /><strong>{label}</strong></button>)}</div><p className={m.note}>{ran ? task.result : "The toy sorter uses these example labels only; it is a simplified model."}</p><button className={s.primary} disabled={task.samples.some((item) => !labels[item.name])} onClick={() => { setRan(true); const wrong = task.samples.find((item) => labels[item.name] !== item.kind); submit(!wrong, wrong ? `${wrong.name} was labelled incorrectly. Change the example and test again.` : task.result); }} type="button"><Play aria-hidden="true" /> Train and test</button></div></div>;
}
export function TeachPetMachine(props: Props) { const p = usePractice(props); const task = petTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Pet machine trainer" brief="A machine learns from labelled examples. Feed it examples, test it, and add what it missed." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="ai"><PetTrainer key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const dogTasks = [
  { prompt: "Label two different dog photos for the training set.", items: [{ name: "Golden retriever", dog: true, image: "golden" }, { name: "Indie dog", dog: true, image: "indie" }, { name: "Backpack", dog: false, image: "bag" }] },
  { prompt: "The model missed a small dog. Find the missing example.", items: [{ name: "Pug", dog: true, image: "pug" }, { name: "Golden retriever", dog: true, image: "golden" }, { name: "Toy dog", dog: false, image: "toy" }] },
  { prompt: "Build a broader test set before trusting the model.", items: [{ name: "Indie puppy", dog: true, image: "indie" }, { name: "Pug", dog: true, image: "pug" }, { name: "Toy dog", dog: false, image: "toy" }] },
];
function DogTrainer({ stage, task, submit }: { stage: number; task: (typeof dogTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [labels, setLabels] = useState<Record<string, boolean>>({}); const [ran, setRan] = useState(false);
  return <div className={m.duo}><div className={m.panel}><h3>{stage === 1 ? "Missed breed test" : "Photo training set"}</h3><div className={m.photoGrid}>{task.items.map((item) => <button aria-pressed={labels[item.name] !== undefined} className={m.dogPhoto} data-dog={item.image} key={item.name} onClick={() => { setRan(false); setLabels((current) => ({ ...current, [item.name]: current[item.name] === undefined ? true : !current[item.name] })); }} type="button"><span className={m.photoImage}>{item.image === "bag" ? <CircleHelp aria-hidden="true" /> : item.image === "toy" ? <Bot aria-hidden="true" /> : null}</span><strong>{item.name}</strong><small>{labels[item.name] === undefined ? "Tap to label" : labels[item.name] ? "Dog" : "Not dog"}</small></button>)}</div><p className={m.note}>Tap each card to switch its label between dog and not dog.</p></div><div className={m.panel}><h3>Model check</h3><div className={m.modelScreen}><PawPrint aria-hidden="true" /><strong>{ran ? "DATASET CHECKED" : "WAITING FOR LABELS"}</strong><span>{ran ? stage === 1 ? "Pug added to training examples" : "Different examples included" : "A narrow dataset may miss a new breed."}</span></div><p>This is a simplified simulation: a real recognizer needs far more varied, reviewed photos.</p><button className={s.primary} disabled={task.items.some((item) => labels[item.name] === undefined)} onClick={() => { setRan(true); const wrong = task.items.find((item) => labels[item.name] !== item.dog); submit(!wrong, wrong ? `${wrong.name} has the wrong label. Correct it before trusting the model.` : stage === 1 ? "The missed breed is now represented. Test beyond one familiar kind of dog." : "The data now includes different dog examples and a non-dog check."); }} type="button"><Play aria-hidden="true" /> Test dataset</button></div></div>;
}
export function TrainingDay(props: Props) { const p = usePractice(props); const task = dogTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Dog dataset lab" brief="If training examples leave out a kind of dog, a recognizer may fail on it. Label and test a broader set." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="ai"><DogTrainer key={p.stage} stage={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const hiringTasks = [
  { prompt: "Audit three fictional library-helper applicants. Mark who has the required skills.", candidates: [{ name: "Asha", school: "School A", skills: 3, qualified: true }, { name: "Dev", school: "School B", skills: 3, qualified: true }, { name: "Ravi", school: "School A", skills: 1, qualified: false }] },
  { prompt: "The old model accepts only School A. Find the unfair feature and switch it off.", candidates: [{ name: "Asha", school: "School A", skills: 3, qualified: true }, { name: "Dev", school: "School B", skills: 3, qualified: true }] },
  { prompt: "Run a fairer rule on a new applicant from School C.", candidates: [{ name: "Nila", school: "School C", skills: 3, qualified: true }, { name: "Sam", school: "School A", skills: 1, qualified: false }] },
];
function HiringAudit({ stage, task, submit }: { stage: number; task: (typeof hiringTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [selected, setSelected] = useState<string[]>([]); const [schoolRule, setSchoolRule] = useState(stage !== 0); const [ran, setRan] = useState(false);
  const target = task.candidates.filter((c) => c.qualified).map((c) => c.name);
  return <div className={m.duo}><div className={m.panel}><h3>Fictional applicant cards</h3><div className={m.stack}>{task.candidates.map((c) => <button aria-pressed={selected.includes(c.name)} className={m.candidate} key={c.name} onClick={() => setSelected((current) => current.includes(c.name) ? current.filter((name) => name !== c.name) : [...current, c.name])} type="button"><span className={m.postAvatar}>{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.school} · {c.skills}/3 required skills</small></span>{selected.includes(c.name) ? <Check aria-hidden="true" /> : null}</button>)}</div><p className={m.note}>Tap applicants who meet the skill requirement.</p></div><div className={m.panel}><h3>Rule engine</h3><button aria-pressed={schoolRule} className={m.toggleRow} onClick={() => setSchoolRule((value) => !value)} type="button"><span>Use school name in decision</span><i data-on={schoolRule} /></button><p>Required skill badges: 3 of 3. School name is unrelated to the job.</p><div className={m.modelScreen}><Filter aria-hidden="true" /><strong>{ran ? schoolRule ? "BIASED RULE ACTIVE" : "SKILLS RULE ACTIVE" : "READY TO TEST"}</strong><span>{ran ? schoolRule ? "Qualified applicants from other schools may be rejected." : "Every applicant is judged on the same skills." : "Run the rule to compare it with your choices."}</span></div><button className={s.primary} onClick={() => { setRan(true); const goodLabels = selected.length === target.length && selected.every((name) => target.includes(name)); const good = goodLabels && (stage === 0 || !schoolRule); submit(good, !goodLabels ? "Check the skill badges, not the school label. Correct the applicants and test again." : schoolRule && stage > 0 ? "The school-name rule still rejects qualified people from other schools. Switch it off." : "Qualified applicants are treated the same regardless of school."); }} type="button"><Play aria-hidden="true" /> Run hiring test</button></div></div>;
}
export function GarbageInGarbageOut(props: Props) { const p = usePractice(props); const task = hiringTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Data fairness lab" brief="A system trained on flawed past decisions can repeat them. Compare applicants by skills, then repair the rule." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="ai"><HiringAudit key={p.stage} stage={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const mediaTasks = [
  { prompt: "A surprising school announcement clip appears with no source. Investigate before sharing.", claim: "School closes tomorrow!", clues: ["No official source listed", "Audio timing looks uneven", "Only one account posted it"], check: "The school's known notice page has no such announcement." },
  { prompt: "A famous voice appears in a short clip. Gather independent context.", claim: "A celebrity endorses a miracle app", clues: ["Unusual mouth and audio timing", "No full interview available", "Account was created today"], check: "The person's verified channel has no matching announcement." },
  { prompt: "A friend sends an urgent edited video. Decide what to do next.", claim: "Forward this immediately", clues: ["Clip begins mid-sentence", "Source is unknown", "Lighting shifts between frames"], check: "A trusted independent source has not confirmed the claim." },
];
function MediaInvestigation({ task, submit }: { task: (typeof mediaTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [seen, setSeen] = useState<number[]>([]); const [checked, setChecked] = useState(false); const [shared, setShared] = useState(false); const [playing, setPlaying] = useState(false); const [played, setPlayed] = useState(false);
  return <div className={m.duo}><div className={m.mediaScreen}><div className={m.mediaFrame} data-playing={playing}><button aria-label={playing ? "Pause simulated clip" : "Play simulated clip"} className={m.playClip} onClick={() => { setPlaying((value) => !value); setPlayed(true); }} type="button">{playing ? <Pause aria-hidden="true" /> : <Play aria-hidden="true" />}</button><span>SIMULATED CLIP · SCRIPTED PRACTICE</span><strong>{task.claim}</strong></div><div className={m.waveform} data-playing={playing}>{Array.from({ length: 29 }, (_, i) => <i key={i} style={{ height: `${20 + ((i * 17) % 55)}%` }} />)}</div><p>{played ? "Now inspect the clues and look for independent confirmation." : "Play the scripted preview, then inspect evidence. No real footage is used."}</p></div><div className={m.panel}><h3>Evidence desk</h3><div className={m.stack}>{task.clues.map((clue, i) => <button aria-pressed={seen.includes(i)} className={m.optionCard} disabled={!played} key={clue} onClick={() => setSeen((current) => current.includes(i) ? current : [...current, i])} type="button"><Search aria-hidden="true" />{seen.includes(i) ? clue : `Inspect clue ${i + 1}`}</button>)}</div><button className={m.sourceButton} disabled={seen.length < 2} onClick={() => setChecked(true)} type="button"><Newspaper aria-hidden="true" /> Check known source</button>{checked ? <p className={m.sourceResult}>{task.check}</p> : null}<div className={m.controls}><button className={s.secondary} disabled={!checked} onClick={() => { setShared(true); submit(false, "One or more clues and a missing source mean this claim is unverified. Pause instead of sharing."); }} type="button">Share clip</button><button className={s.primary} disabled={!checked} onClick={() => submit(true, "You paused an unverified claim and checked a source independent of the clip.")} type="button"><Check aria-hidden="true" /> Hold and verify</button></div>{shared ? <p className={m.note}>Sharing can spread a false claim before it is checked.</p> : null}</div></div>;
}
export function DeepfakeDetective(props: Props) { const p = usePractice(props); const task = mediaTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Media verification desk" brief="Odd details are clues, not proof. Inspect the clip, check an independent source, and decide whether to share." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="media"><MediaInvestigation key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const feedTasks = [
  { prompt: "Click the sensational post twice and watch the feed change.", aim: "observe", headline: "Wild rumour about school rules" },
  { prompt: "The feed is crowded with one topic. Add two different sources.", aim: "widen", headline: "Another shocking rumour" },
  { prompt: "Build a balanced feed after a new clickbait post appears.", aim: "repair", headline: "You will not believe this" },
] as const;
function RabbitHole({ task, submit }: { task: (typeof feedTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [sensational, setSensational] = useState(task.aim === "observe" ? 1 : 4); const [topics, setTopics] = useState<string[]>([]); const [limited, setLimited] = useState(false);
  const diversity = Math.max(10, Math.min(100, 65 - sensational * 12 + topics.length * 24 + (limited ? 20 : 0)));
  return <div className={m.duo}><div className={m.feed}><div className={m.feedHeader}><Filter aria-hidden="true" /><strong>YOUR SIMULATED FEED</strong><span>not a real recommendation system</span></div><button className={m.feedPost} onClick={() => setSensational((value) => Math.min(6, value + 1))} type="button"><span className={m.postAvatar}>!</span><span>{task.headline}<small>Click to see more like this</small></span><ArrowRight aria-hidden="true" /></button>{Array.from({ length: Math.min(4, sensational) }, (_, i) => <div className={m.feedPost} key={i}><span className={m.postAvatar}>!</span><span>Similar rumour #{i + 1}</span></div>)}{topics.map((topic) => <div className={m.feedPost} key={topic}><span className={m.postAvatar}>+</span><span>{topic} update</span></div>)}</div><div className={m.panel}><h3>Feed diversity meter</h3><div className={m.meter}><span style={{ width: `${diversity}%` }} /></div><strong>{diversity}% topic variety</strong><p>{task.aim === "observe" ? "One click is a signal. Try two more to see how the feed narrows." : "Add sources on other topics instead of letting one headline set the whole feed."}</p><div className={m.stack}>{["Science", "Sports", "Local news"].map((topic) => <button className={m.optionCard} disabled={topics.includes(topic)} key={topic} onClick={() => setTopics((current) => [...current, topic])} type="button"><Newspaper aria-hidden="true" /> Follow {topic}</button>)}</div>{task.aim === "repair" ? <button aria-pressed={limited} className={m.toggleRow} onClick={() => setLimited((value) => !value)} type="button"><span>Show fewer clickbait posts</span><i data-on={limited} /></button> : null}<button className={s.primary} disabled={task.aim === "observe" ? sensational < 3 : task.aim === "repair" ? topics.length < 2 || !limited : topics.length < 2} onClick={() => submit(true, task.aim === "observe" ? "The feed repeated the sensational topic after your clicks. Your actions send signals to the system." : "You deliberately widened the feed with more topics and reduced the repeated clickbait signal.")} type="button"><Eye aria-hidden="true" /> {task.aim === "observe" ? "Explain the change" : "Check feed balance"}</button></div></div>;
}
export function RecommendationRabbitHole(props: Props) { const p = usePractice(props); const task = feedTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Feed experiment" brief="Explore a simulated feed. Your clicks change what appears; you can also seek different topics and sources." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="media"><RabbitHole key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }
