"use client";

import { ArrowRight, Backpack, Check, Eye, Gamepad2, KeyRound, LockKeyhole, Mail, Play, RotateCcw, ShieldCheck, Smartphone, UnlockKeyhole } from "lucide-react";
import { useState } from "react";
import type { CyberLessonComponentProps } from "../../lesson-types";
import { PracticeShell, usePractice } from "./PracticeShell";
import s from "./practice.module.css";
import m from "./worlds.module.css";

type Props = CyberLessonComponentProps;

const vaultTasks = [
  { prompt: "Build a long practice passphrase from five unrelated words.", pieces: ["River", "Lantern", "Cloud", "Pebble", "Orbit", "Rohan123", "12345"], good: ["River", "Lantern", "Cloud", "Pebble", "Orbit"] },
  { prompt: "The old code was 'Password123'. Replace it with a new long phrase.", pieces: ["Tiger", "Copper", "Garden", "Maple", "Rocket", "Password", "MyName"], good: ["Tiger", "Copper", "Garden", "Maple", "Rocket"] },
  { prompt: "Make a different key for a second safe. Do not copy the first one.", pieces: ["Harbor", "Comet", "Zebra", "Candle", "Marble", "River", "1111"], good: ["Harbor", "Comet", "Zebra", "Candle", "Marble", "River"] },
];
function VaultPuzzle({ stage, task, ready, submit }: { stage: number; task: (typeof vaultTasks)[number]; ready: boolean; submit: (ok: boolean, feedback: string) => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const good = selected.length === 5 && selected.every((part) => task.good.includes(part));
  return <div className={m.duo}>
    <div className={`${m.vault} ${ready ? m.vaultOpen : ""}`} aria-label={ready ? "Practice safe unlocked" : "Practice safe locked"}>
      <div className={m.vaultChamber}><Gamepad2 aria-hidden="true" /><span>MOONBASE SAVED</span></div>
      <div className={m.vaultDoor}>{ready ? <UnlockKeyhole aria-hidden="true" /> : <LockKeyhole aria-hidden="true" />}<strong>{ready ? "SAFE OPEN" : "CYBERPUR SAFE"}</strong><span>{selected.length}/5 words fitted</span></div>
      <div className={m.codeSlots}>{[0, 1, 2, 3, 4].map((i) => <span key={i}>{selected[i] ?? "?"}</span>)}</div>
      <div className={m.wordMeter} aria-label={`${selected.length} of 5 words fitted`}>{[0, 1, 2, 3, 4].map((i) => <span data-filled={i < selected.length} key={i} />)}</div>
    </div>
    <div className={m.panel}><h3>Fit five unrelated words</h3><p>These are fictional puzzle pieces. Never enter a real password here.</p><div className={m.tileGrid}>{task.pieces.map((part) => <button aria-pressed={selected.includes(part)} className={m.token} disabled={selected.includes(part) || selected.length === 5} key={part} onClick={() => setSelected((current) => [...current, part])} type="button"><KeyRound aria-hidden="true" />{part}</button>)}</div><div className={m.controls}><button className={s.secondary} disabled={!selected.length} onClick={() => setSelected((current) => current.slice(0, -1))} type="button"><RotateCcw aria-hidden="true" /> Undo</button><button className={s.primary} disabled={selected.length !== 5} onClick={() => submit(good, good ? stage === 2 ? "New safe, new long key. The two accounts do not reuse a secret." : "The safe opens. Five unrelated words make a longer practice phrase." : "That phrase includes a predictable code. Undo and try five unrelated words.")} type="button"><Play aria-hidden="true" /> Test safe</button></div></div>
  </div>;
}
export function PasswordVaultBuilder(props: Props) { const p = usePractice(props); const task = vaultTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Rohan’s password lab" brief="Fit a long, memorable practice phrase together. Never use a real password in a lesson." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="fair-vault"><VaultPuzzle key={p.stage} stage={p.stage} task={task} ready={p.ready} submit={p.submit} /></PracticeShell>; }

type Bag = "Share in class" | "Keep private" | "Ask an adult";
const bags: Bag[] = ["Share in class", "Keep private", "Ask an adult"];
const bagTasks: { prompt: string; items: { name: string; bag: Bag; why: string }[] }[] = [
  { prompt: "Pack these three details into the right bags.", items: [{ name: "Favourite colour", bag: "Share in class", why: "A favourite colour does not identify where you live." }, { name: "Home address", bag: "Keep private", why: "An address can reveal where you live." }, { name: "Selfie for a public page", bag: "Ask an adult", why: "A photo can reveal more than you expect; ask before posting." }] },
  { prompt: "A new game asks about you. Pack its requests safely.", items: [{ name: "Favourite book", bag: "Share in class", why: "A book preference is usually safe in a class activity." }, { name: "Phone number", bag: "Keep private", why: "A phone number is personal contact information." }, { name: "Photo of a classmate", bag: "Ask an adult", why: "Check consent and the audience before sharing someone else's photo." }] },
  { prompt: "Transfer the habit to a class project page.", items: [{ name: "Favourite game", bag: "Share in class", why: "A game preference can be shared in a class setting." }, { name: "Live location", bag: "Keep private", why: "Live location reveals where you are right now." }, { name: "Team photo", bag: "Ask an adult", why: "Get permission from everyone and check where the photo will go." }] },
];
function BackpackSort({ task, submit }: { task: (typeof bagTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [active, setActive] = useState<string | null>(null); const [placed, setPlaced] = useState<Record<string, Bag>>({});
  function place(bag: Bag) { if (active) { setPlaced((current) => ({ ...current, [active]: bag })); setActive(null); } }
  const allPlaced = task.items.every((item) => placed[item.name]);
  return <div className={m.panel}><div className={m.tray}><h3>Tap an item, then tap a backpack</h3><div className={m.tileGrid}>{task.items.map((item) => <button aria-pressed={active === item.name} className={m.itemTile} key={item.name} onClick={() => setActive(item.name)} type="button"><Backpack aria-hidden="true" /><strong>{item.name}</strong><small>{placed[item.name] ?? "Not packed"}</small></button>)}</div></div><div className={m.bags}>{bags.map((bag) => <button className={m.bag} disabled={!active} key={bag} onClick={() => place(bag)} type="button"><Backpack aria-hidden="true" /><strong>{bag}</strong><small>{Object.values(placed).filter((value) => value === bag).length} packed</small></button>)}</div><button className={s.primary} disabled={!allPlaced} onClick={() => { const wrong = task.items.find((item) => placed[item.name] !== item.bag); submit(!wrong, wrong ? `${wrong.name}: ${wrong.why} Move it and check again.` : "Every item is in the right bag. You considered the audience and consent."); }} type="button"><Check aria-hidden="true" /> Check backpacks</button></div>;
}
export function SharingBackpack(props: Props) { const p = usePractice(props); const task = bagTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Privacy packing" brief="Decide what belongs in a class conversation, what stays private, and what needs an adult's help." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="vault"><BackpackSort key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const accounts = [
  { prompt: "Choose a long key for the fictional game account.", name: "Cyberpur Games", keys: ["BlueRiverLantern47", "Game123", "password"] as string[], answer: "BlueRiverLantern47" },
  { prompt: "Protect the school account with a different long key.", name: "Class Project", keys: ["BlueRiverLantern47", "CopperGardenMoon82", "school123"] as string[], answer: "CopperGardenMoon82" },
];
function AccountKeys({ stage, ready, submit }: { stage: number; ready: boolean; submit: (ok: boolean, feedback: string) => void }) {
  const task = accounts[Math.min(stage, 1)]; const [selected, setSelected] = useState(""); const [repaired, setRepaired] = useState(false); const [tested, setTested] = useState(false);
  if (stage === 2) return <div className={m.duo}><div className={m.panel}><h3>Leak simulation</h3><p>Both accounts accidentally used the same pretend key. Tap the school account to give it a new one, then run the leak.</p><div className={m.account}><Smartphone aria-hidden="true" /><strong>Game account</strong><span className={tested ? m.risk : ""}>{tested ? "Exposed" : "Shared key"}</span></div><button className={m.account} onClick={() => setRepaired(true)} type="button"><KeyRound aria-hidden="true" /><strong>School account</strong><span className={tested ? repaired ? m.safe : m.risk : ""}>{tested ? repaired ? "Still safe" : "Also exposed" : repaired ? "New unique key" : "Shared key · tap to replace"}</span></button></div><div className={m.panel}><h3>Domino test</h3><div className={m.dominoes}><span data-fallen={tested}>GAME</span><ArrowRight aria-hidden="true" /><span data-fallen={tested && !repaired}>SCHOOL</span></div><p>{tested ? repaired ? "Only the leaked game account is exposed. The separate school key blocked the domino." : "Both accounts fell because the key was reused. Replace the school key and run again." : "Run a fictional game-account leak to see what reuse changes."}</p><button className={s.primary} onClick={() => { setTested(true); submit(repaired, repaired ? "A unique key prevented the second account from falling." : "Reuse made both accounts vulnerable. Give school its own key, then rerun."); }} type="button"><Play aria-hidden="true" /> Run leak</button></div></div>;
  return <div className={m.duo}><div className={m.panel}><h3>{task.name}</h3><div className={`${m.accountVault} ${ready ? m.accountVaultOpen : ""}`}><KeyRound aria-hidden="true" /><strong>{ready ? "LOCKED WITH UNIQUE KEY" : "ACCOUNT NEEDS A KEY"}</strong></div><p>Practice keys only. Never type a real password into a lesson.</p></div><div className={m.panel}><h3>Choose a key, then test</h3><div className={m.stack}>{task.keys.map((key) => <button aria-pressed={selected === key} className={m.optionCard} key={key} onClick={() => setSelected(key)} type="button"><KeyRound aria-hidden="true" />{key}</button>)}</div><button className={s.primary} disabled={!selected} onClick={() => submit(selected === task.answer, selected === task.answer ? stage === 1 ? "Different accounts now have different long keys." : "The game account has a longer practice key." : selected === "BlueRiverLantern47" && stage === 1 ? "That key already protects the game account. Choose a different one." : "Short or common keys are easier to guess. Try a longer one.")} type="button"><Play aria-hidden="true" /> Test account</button></div></div>;
}
export function PasswordVault(props: Props) { const p = usePractice(props); return <PracticeShell props={props} stage={p.stage} eyebrow="Account key lab" brief="A long key is useful; a different key for each account limits what one leak can expose." prompt={p.stage >= 2 ? "Stop the reuse domino before you run a pretend leak." : accounts[p.stage].prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="vault"><AccountKeys key={p.stage} stage={p.stage} ready={p.ready} submit={p.submit} /></PracticeShell>; }

type Permission = "Camera" | "Contacts" | "Location";
const permissionTasks: { prompt: string; app: string; needed: Permission[]; reason: string }[] = [
  { prompt: "A flashlight app wants three permissions. Grant only what it needs.", app: "Pocket Torch", needed: [], reason: "A basic flashlight needs none of these three permissions." },
  { prompt: "A map app needs to show your position. Set minimum access.", app: "City Map", needed: ["Location"], reason: "Location helps show your position; camera and contacts are unrelated here." },
  { prompt: "A video call app needs to show your face. Set minimum access.", app: "Class Video", needed: ["Camera"], reason: "Camera supports video; contacts and location are unnecessary for this practice call." },
];
function PermissionBoard({ task, submit }: { task: (typeof permissionTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [on, setOn] = useState<Permission[]>(["Camera", "Contacts", "Location"]); const [tested, setTested] = useState(false);
  return <div className={m.duo}><div className={m.appPhone}><Smartphone aria-hidden="true" /><small>Fictional app request</small><h3>{task.app}</h3><div className={m.permissionRows}>{(["Camera", "Contacts", "Location"] as Permission[]).map((permission) => <button aria-pressed={on.includes(permission)} className={m.toggleRow} key={permission} onClick={() => { setTested(false); setOn((current) => current.includes(permission) ? current.filter((p) => p !== permission) : [...current, permission]); }} type="button"><span>{permission}</span><i data-on={on.includes(permission)} /></button>)}</div></div><div className={m.panel}><h3>Access monitor</h3><div className={m.meter}><span style={{ width: `${Math.max(8, 100 - on.length * 28)}%` }} /></div><p>{on.length ? `${on.length} permissions enabled.` : "No extra permissions enabled."}</p><p className={m.note}>{tested ? task.reason : "Switch off access the app does not need, then test it."}</p><button className={s.primary} onClick={() => { setTested(true); const good = on.length === task.needed.length && on.every((item) => task.needed.includes(item)); submit(good, good ? `Minimum access set. ${task.reason}` : `Check each switch. ${task.reason}`); }} type="button"><Play aria-hidden="true" /> Test app access</button></div></div>;
}
export function PermissionControlPanel(props: Props) { const p = usePractice(props); const task = permissionTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Access control" brief="An app should get only the access needed for its job. Toggle the requests and test your choice." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="vault"><PermissionBoard key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }

const reputationTasks = [
  { prompt: "A scholarship reviewer can see this fictional public feed. Select posts to revise.", posts: [{ text: "Built a library book exchange with classmates.", revise: false }, { text: "Posted a classmate's photo without asking.", revise: true }, { text: "Mocked a teammate after a disagreement.", revise: true }] },
  { prompt: "Repair this public post without hiding what you learned.", posts: [{ text: "Our team lost because Maya is useless.", revise: true }, { text: "Our team struggled. Next time I'll listen and plan better.", revise: false }, { text: "Delete every record of the project.", revise: true }] },
  { prompt: "A location post is ready to publish. Choose a safer audience.", posts: [{ text: "Post my live route publicly.", revise: true }, { text: "Share a project update without location details.", revise: false }, { text: "Tag friends at their homes without asking.", revise: true }] },
];
function FeedEditor({ stage, task, ready, submit }: { stage: number; task: (typeof reputationTasks)[number]; ready: boolean; submit: (ok: boolean, feedback: string) => void }) {
  const [marked, setMarked] = useState<number[]>([]); const single = stage > 0;
  function toggle(i: number) { setMarked((current) => single ? [i] : current.includes(i) ? current.filter((x) => x !== i) : [...current, i]); }
  const good = single ? marked.length === 1 && !task.posts[marked[0]].revise : marked.length === task.posts.filter((post) => post.revise).length && marked.every((i) => task.posts[i].revise);
  return <div className={m.duo}><div className={m.feed}><div className={m.feedHeader}><Eye aria-hidden="true" /><strong>PUBLIC PREVIEW</strong><span>Fictional profile</span></div>{task.posts.map((post, i) => <button aria-pressed={marked.includes(i)} className={m.feedPost} key={post.text} onClick={() => toggle(i)} type="button"><span className={m.postAvatar}>{i + 1}</span><span>{post.text}</span>{marked.includes(i) ? <Check aria-hidden="true" /> : null}</button>)}</div><div className={m.panel}><h3>{single ? "Choose the post to publish" : "Mark posts that need repair"}</h3><p>{single ? "A public post can be seen later and out of context. Make the useful part clear and respect others." : "A useful project post can stay. Consent and respectful language matter when a profile is public."}</p><div className={m.reputationStamp}>{ready ? <ShieldCheck aria-hidden="true" /> : <Eye aria-hidden="true" />}<span>{ready ? "Profile reviewed" : `${marked.length} selected`}</span></div><button className={s.primary} disabled={single ? marked.length !== 1 : marked.length === 0} onClick={() => submit(good, good ? single ? "This version keeps the useful message without exposing or insulting someone." : "You identified the posts that need consent or a respectful rewrite." : single ? "That version still reveals too much or harms someone. Choose a better public post." : "Review consent and tone. A constructive project update can stay public.")} type="button"><Check aria-hidden="true" /> {single ? "Publish preview" : "Review profile"}</button></div></div>;
}
export function OnlineReputationBuilder(props: Props) { const p = usePractice(props); const task = reputationTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Public profile studio" brief="Review fictional posts as if a scholarship team might read them later. Repair what harms privacy or trust." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="media"><FeedEditor key={p.stage} stage={p.stage} task={task} ready={p.ready} submit={p.submit} /></PracticeShell>; }

const emailTasks = [
  { prompt: "A message claims to be from the scholarship office. Reveal the header and tap the suspicious field.", subject: "Confirm your award today", display: "Scholarship Office", from: "awards@school-prizes.example", reply: "claims@school-prizes.example", evidence: "From", why: "The actual sender uses school-prizes.example, not the school's official address." },
  { prompt: "This reply route points somewhere else. Find the mismatch.", subject: "Your interview invitation", display: "School Awards", from: "awards@school.example", reply: "forms@instant-awards.example", evidence: "Reply-To", why: "Replies would go to an unrelated domain. Verify through the school's known site." },
  { prompt: "A new message asks for a fee. Inspect before you act.", subject: "Pay the award release fee", display: "Awards Team", from: "cashier@claim-now.example", reply: "cashier@claim-now.example", evidence: "From", why: "The sender is not the known school domain; do not pay or reply from this message." },
];
function HeaderInspector({ task, submit }: { task: (typeof emailTasks)[number]; submit: (ok: boolean, feedback: string) => void }) {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState("");
  return <div className={m.duo}><div className={m.emailCard}><div className={m.emailTop}><Mail aria-hidden="true" /><span>Fictional inbox</span></div><strong>{task.subject}</strong><p>From: {task.display}</p><p>Please act soon. Use the reply button to continue.</p><button className={s.secondary} onClick={() => setOpen((value) => !value)} type="button"><Eye aria-hidden="true" /> {open ? "Hide" : "Reveal"} technical header</button>{open ? <div className={m.headerRows}>{(["Display name", "From", "Reply-To"] as const).map((field) => <button aria-pressed={selected === field} className={m.headerRow} key={field} onClick={() => setSelected(field)} type="button"><small>{field}</small><span>{field === "Display name" ? task.display : field === "From" ? task.from : task.reply}</span></button>)}</div> : null}</div><div className={m.panel}><h3>Inspect the route</h3><p>Names shown at the top can be faked. The full address and reply route give more useful clues.</p><div className={m.reputationStamp}><Mail aria-hidden="true" /><span>{selected ? `${selected} selected` : "No header field selected"}</span></div><button className={s.primary} disabled={!selected} onClick={() => submit(selected === task.evidence, selected === task.evidence ? `${task.why} Keep the message unverified and use an independent school contact.` : "That label alone does not reveal the key mismatch. Inspect the full addresses.")} type="button"><Check aria-hidden="true" /> Check evidence</button></div></div>;
}
export function EmailHeaderInspector(props: Props) { const p = usePractice(props); const task = emailTasks[Math.min(p.stage, 2)]; return <PracticeShell props={props} stage={p.stage} eyebrow="Inbox forensics" brief="Expand a fictional email header. Compare the display name with where the message and replies actually go." prompt={task.prompt} feedback={p.feedback} feedbackCorrect={p.feedbackCorrect} ready={p.ready} onContinue={p.continuePractice} onFinish={p.finish} art="media"><HeaderInspector key={p.stage} task={task} submit={p.submit} /></PracticeShell>; }
