"use client";

import { AlertTriangle, ArrowRight, Bot, Eye, LockKeyhole, PhoneIncoming, Route, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { CyberLessonMeta } from "../../../../data/cyber-lessons";
import s from "./story.module.css";

type Probe = { label: string; reveal: string };
type Story = { hook: string; setup: string; speaker: string; line: string; artifact: string; probes: [Probe, Probe]; insight: string };

export const stories: Record<string, Story> = {
  "password-vault-builder": { hook: "Rohan’s moon base is locked.", setup: "Someone guessed his short game password. Mum helps him recover his account.", speaker: "Rohan", line: "Can we make a password that is harder to guess?", artifact: "Moonbase account", probes: [{ label: "Try Rohan123", reveal: "His name and 123 make a predictable password." }, { label: "Join two pieces", reveal: "Mango! and Rocket482? join into a password with words you know." }], insight: "Make real passwords privately. Use a different full password for each account." },
  "sharing-backpack": { hook: "The class noticeboard is open to everyone.", setup: "Nani wants to post a picnic note, but some details would tell strangers too much.", speaker: "Nani", line: "Which things are fine for a class chat, and which need to stay with us?", artifact: "Public picnic board", probes: [{ label: "Pin a favourite colour", reveal: "A favourite colour says little about where someone lives." }, { label: "Pin a home address", reveal: "An address points to a real home. Keep it off a public board." }], insight: "Who can see a post changes what is safe to share. Ask an adult about photos of people." },
  "password-vault": { hook: "One leaked key starts a domino.", setup: "A pretend game account was breached. Its key also opens a school account.", speaker: "Security desk", line: "How far can one stolen key travel?", artifact: "Two connected accounts", probes: [{ label: "Reuse one key", reveal: "The second account becomes exposed when both use the same key." }, { label: "Give each a key", reveal: "A different key keeps the school account out of this leak." }], insight: "Use a different password for every account. Length and uniqueness matter more than tricky symbol rules." },
  "permission-control-panel": { hook: "A flashlight asks to see your contacts.", setup: "The new app also asks for camera and location access before it turns on its light.", speaker: "App request", line: "Allow everything to continue?", artifact: "Permission request", probes: [{ label: "Open contacts access", reveal: "A flashlight does not need the names and numbers in your contacts." }, { label: "Check what light needs", reveal: "The basic light can work without camera, contacts, or location access." }], insight: "Give an app only the access it needs for its actual job." },
  "online-reputation-builder": { hook: "A scholarship team opens a public profile.", setup: "They see a thoughtful project update beside an unkind comment and a class photo posted without asking.", speaker: "Future you", line: "I wish I had looked at what everyone could see.", artifact: "Public profile preview", probes: [{ label: "View the unkind post", reveal: "A public comment can outlast the moment when it felt funny." }, { label: "View the class photo", reveal: "Someone else's image needs their permission before you share it." }], insight: "Pause before posting: consider the audience, the people pictured, and how the post may read later." },
  "email-header-inspector": { hook: "The name says ‘School Office.’ The address doesn't.", setup: "A scholarship email asks for details quickly. The display name looks official, but the hidden address tells another story.", speaker: "Inbox alert", line: "Open the form before midnight to claim your award.", artifact: "Message header", probes: [{ label: "Reveal the From address", reveal: "The real sender domain can differ from the friendly name shown first." }, { label: "Reveal the Reply-To", reveal: "Replies can be routed to yet another address controlled by the sender." }], insight: "A display name is not proof. Inspect the full address and verify through a known school channel." },
  "robot-or-not": { hook: "The dancing robot says hello.", setup: "A puppy barks back. Both move, but only one grows and needs food and care.", speaker: "Cyberpur lab", line: "Does moving and talking make the robot alive?", artifact: "Robot and puppy", probes: [{ label: "Watch the robot", reveal: "Its moves and words follow a program made by people." }, { label: "Watch the puppy", reveal: "The puppy grows, eats, and responds as a living animal." }], insight: "A machine can act lively without being alive. Look for growth and life needs." },
  "teach-pet-machine": { hook: "The pet sorter calls a rock ‘fruit.’", setup: "It saw one round apple and guessed that every round thing belongs in the fruit basket.", speaker: "Pet machine", line: "Round thing found. Fruit?", artifact: "Training tray", probes: [{ label: "Show an apple", reveal: "The machine has seen this kind of fruit before." }, { label: "Show a round rock", reveal: "This example proves shape alone is not enough. The sorter needs more labels." }], insight: "A machine learns from examples. Better, varied examples help it avoid silly guesses." },
  "training-day": { hook: "The dog camera misses a real dog.", setup: "Its training photos mostly show one breed. An indie dog walks into view and the camera hesitates.", speaker: "Camera model", line: "I know the golden retriever. What is this new shape?", artifact: "Dog photo set", probes: [{ label: "Check known photos", reveal: "The model recognizes what its training set included." }, { label: "Check missing breeds", reveal: "Leaving out other dogs makes the model less reliable for them." }], insight: "Test a model on varied examples, especially the kinds it might have missed." },
  "garbage-in-garbage-out": { hook: "Two skilled applicants get different scores.", setup: "A pretend hiring helper copied an old rule that favoured one school name over actual skills.", speaker: "Review team", line: "Their skills match. Why did the tool choose only one?", artifact: "Hiring rule", probes: [{ label: "Compare skills", reveal: "Both applicants meet the same job requirements." }, { label: "Expose school rule", reveal: "The tool uses an unrelated school label. That can create an unfair result." }], insight: "A system can repeat a flawed rule. Check the data and judge people by relevant skills." },
  "deepfake-detective": { hook: "A shocking school clip arrives without a source.", setup: "The video claims school closes tomorrow. It looks polished enough to spread quickly.", speaker: "Class group", line: "Should we forward it now?", artifact: "Unverified clip", probes: [{ label: "Inspect the clip", reveal: "Odd audio or visuals can be clues, but they do not prove a clip is fake." }, { label: "Check school source", reveal: "A known school channel can confirm or contradict the claim independently." }], insight: "Hold the share button. Check an independent source before trusting a surprising clip." },
  "recommendation-rabbit-hole": { hook: "One wild clip changes the whole feed.", setup: "The app notices every pause and click. Soon similar posts crowd out other topics.", speaker: "Feed engine", line: "You watched that one. Want twelve more?", artifact: "Suggestion feed", probes: [{ label: "Replay the rumour", reveal: "Repeated attention tells the feed to show more of the same topic." }, { label: "Seek another topic", reveal: "Following varied topics gives the feed a wider signal." }], insight: "Recommendations react to behaviour. Choose varied sources instead of letting one click choose for you." },
  "pattern-detective": { hook: "Nani's trolley stops at a missing tile.", setup: "The station track has a rhythm. A new tile must match the repeating group before the trolley can roll.", speaker: "Nani", line: "Can you spot what the track is trying to repeat?", artifact: "Trolley track", probes: [{ label: "Trace the first group", reveal: "Look for the smallest group of shapes that repeats." }, { label: "Trace the next group", reveal: "The same order appears again. The missing tile continues it." }], insight: "A pattern is a repeated rule. Find the group, then predict what comes next." },
  "step-by-step-morning": { hook: "The morning robot puts on shoes before socks.", setup: "It followed the steps exactly as written. Now it is stuck at the door.", speaker: "Morning robot", line: "Instruction complete. Why is this uncomfortable?", artifact: "Routine cards", probes: [{ label: "Run the bad order", reveal: "A computer follows a sequence even when the result makes no sense." }, { label: "Move the first step", reveal: "Putting actions in a useful order changes the outcome." }], insight: "A sequence is an ordered set of steps. Change the order, and you change the result." },
  "flowchart-architect": { hook: "The wash station sprays an empty sink.", setup: "Its plan skips the question ‘Are hands here?’ and dispenses soap every time.", speaker: "Workshop team", line: "We need the station to decide before it acts.", artifact: "Sensor path", probes: [{ label: "Test: hands present", reveal: "A YES path can dispense soap and continue washing." }, { label: "Test: no hands", reveal: "A NO path should wait. The decision diamond separates the two outcomes." }], insight: "A flowchart shows actions and decisions. Test both sides of a question." },
  "loop-inspector": { hook: "The cleaner's program repeats itself four times.", setup: "Four identical commands fill the screen. The robot can do the same work with a shorter instruction.", speaker: "Robot cleaner", line: "MOVE RIGHT. MOVE RIGHT. MOVE RIGHT. MOVE RIGHT.", artifact: "Robot command strip", probes: [{ label: "Run the long list", reveal: "The robot moves four steps, one command at a time." }, { label: "Run REPEAT 4", reveal: "One loop runs the same command four times with less code." }], insight: "A loop repeats an action. The repeat count must match the work you want done." },
  "complex-algorithmic-logic": { hook: "A score of exactly 40 gets the wrong result.", setup: "The grade processor says ‘retry’ even though 40 should pass. One symbol in the rule is missing.", speaker: "Test console", line: "38: retry · 40: retry · 74: pass", artifact: "Boundary test", probes: [{ label: "Test score 39", reveal: "39 should retry, so the rule must still reject scores below 40." }, { label: "Test score 40", reveal: "40 should pass. The rule needs ≥ rather than >." }], insight: "Test the boundary value. A tiny condition change can change someone's outcome." },
  "algorithm-optimization": { hook: "Two sorters finish with the same order.", setup: "One makes many comparisons; the other groups its work. The winner changes with the size and order of the list.", speaker: "Sorting lab", line: "Same answer. Did they do the same amount of work?", artifact: "Comparison race", probes: [{ label: "Try a small sorted list", reveal: "Bubble sort can stop early when nothing needs swapping." }, { label: "Try a larger mixed list", reveal: "Merge sort usually uses fewer comparisons as mixed lists grow." }], insight: "Correct output is only part of the story. Measure the work an algorithm does." },
  "nanis-secret-code": { hook: "A stranger calls about Nani's parcel.", setup: "They sound helpful, but they ask for the one-time code that just appeared on her phone.", speaker: "Unknown caller", line: "Read me the six digits. The parcel is waiting.", artifact: "Incoming call", probes: [{ label: "Look at the code", reveal: "The code is a temporary key. Sharing it gives someone else power to act." }, { label: "Look at the caller", reveal: "A friendly voice is not proof of identity. The request is the warning sign." }], insight: "Keep one-time codes private. End the call and tell Nani or another trusted adult." },
  "surprise-pop-up": { hook: "A prize window covers the game.", setup: "Nobody entered a contest, but the screen says a free tablet is waiting behind a big claim button.", speaker: "Pop-up", line: "Claim your prize before the timer ends!", artifact: "Game overlay", probes: [{ label: "Inspect the claim button", reveal: "A surprise offer tries to pull you away from the game." }, { label: "Find the close control", reveal: "Closing the overlay clears the game without following its instructions." }], insight: "Unexpected prize windows are easy to close. Do not enter codes or install their helpers." },
  "otp-guardian": { hook: "A ‘bank officer’ asks for an OTP.", setup: "The caller says the card is frozen and the secret code will fix it immediately.", speaker: "Unknown number", line: "Tell me the OTP now or your account will stop working.", artifact: "Pressure call", probes: [{ label: "Inspect the title", reveal: "A caller can claim to be bank staff. The title itself proves nothing." }, { label: "Inspect the request", reveal: "The caller wants an OTP. That is the risky action, whatever their title." }], insight: "Never give an OTP to a caller. Use a known official channel if you need to check an issue." },
  "qr-code-caution": { hook: "The buyer says ‘receive ₹500.’ The phone says ‘Pay ₹500.’", setup: "A QR scan has opened a pretend payment screen. The two descriptions point in opposite directions.", speaker: "Buyer", line: "Enter your PIN. It is just verification.", artifact: "Payment direction", probes: [{ label: "Read the Pay label", reveal: "The screen shows money leaving your account, not arriving." }, { label: "Inspect the PIN request", reveal: "A UPI PIN authorizes a payment. It is not needed to receive money." }], insight: "Read the payment direction yourself. Cancel a debit you did not mean to make." },
  "digital-arrest-simulation": { hook: "A fake officer orders you to stay on the call.", setup: "They demand secrecy and a fee while claiming you are under ‘digital arrest.’", speaker: "Unknown video caller", line: "Do not tell anyone. Pay now or your family is in trouble.", artifact: "Intimidation call", probes: [{ label: "Inspect the secrecy demand", reveal: "Isolation makes it harder to ask a trusted person for help." }, { label: "Inspect the fee demand", reveal: "The urgent payment demand is another warning sign of this scam." }], insight: "End the call, tell a trusted adult, and use an official reporting channel in India." },
  "deepfake-voice-relative-scam": { hook: "An urgent voice note sounds like your uncle.", setup: "The number is unknown. The voice asks for money and says not to call anyone else.", speaker: "Voice note", line: "It is me. Send money quickly. My old phone is broken.", artifact: "Unknown voice note", probes: [{ label: "Listen to the voice", reveal: "A familiar sound can be imitated. Voice alone is not identity proof." }, { label: "Check the number", reveal: "The request came from an unknown route. Call a saved number or another known contact." }], insight: "Pause the payment until you verify through a contact route you already trust." },
};

/** Scene direction for the three practice turns, followed by the story payoff. */
export const storyArcs: Record<string, [string, string, string, string]> = {
  "password-vault-builder": ["Rohan is back in his game. Join two familiar word tiles, keeping their numbers and symbols.", "A friend used Password123. Build a different practice password without a common pattern.", "Rohan needs a different full password for his school account. Build a new practice password for it.", "Rohan knows to use a long, hard-to-guess password and give each account its own. An adult can help a password manager make and save them."],
  "sharing-backpack": ["Rohan's drawing club profile is saved. Help him sort three more details: what's fine to share, what stays private, and what needs a grown-up first.", "A new drawing game asks Rohan about himself, including his phone number and a photo of his classmate. Help him choose safely.", "Rohan's class is making a project page with his tiger on it. Sort one last set before the page goes live.", "Rohan shares his tigers and favourite things, while his address, live location and people's photos stay with his family."],
  "password-vault": ["Tara is replacing an easy-to-guess game password. Join two familiar word tiles, with numbers and symbols.", "Her school account needs its own password. Build a different one, then test it against the leaked game password.", "Build a different email password, then replay the game breach to see which accounts the stolen game password opens.", "The stolen game password opened only the game. Tara's school and email passwords were different, so those doors stayed closed."],
  "permission-control-panel": ["Cousin Meera's friend downloaded a torch app too. Help Tara check Pocket Torch's requests and switch off everything a light doesn't need.", "Tara needs directions to the Cyberpur science fair. Give City Map only the access it needs to show where she is.", "Tara's class is meeting on a video call. Work out what Class Video really needs to show her face, and switch off the rest.", "Every app on Tara's phone can do its job, and her contacts and location stay private unless an app truly needs them."],
  "online-reputation-builder": ["Kabir's audit worked. Now review another pretend public feed the way a scholarship reviewer would, and mark every post that needs consent or a kinder rewrite.", "After a tough science-club match, a teammate's draft blames someone by name. Help Kabir choose the public post that owns the loss and shows what he learned.", "Kabir wants to share his next build. Help him pick an update that shows the project without revealing anyone's location or tagging friends without asking.", "Kabir's public profile now shows real work, respect and consent, and he pauses to ask who will see a post before he shares it."],
  "email-header-inspector": ["Kabir's inbox pings again: another 'Scholarship Office' email says 'Confirm your award today'. Help him reveal the header and tap the field that gives it away.", "This one looks like it's from School Awards, but a reply would go somewhere else. Help Kabir find where the Reply-To really points.", "One last email asks Kabir to 'pay the award release fee'. Inspect the sender before anyone pays or replies.", "Kabir checked where every email really came from before trusting it. Now he looks past the display name every time."],
  "robot-or-not": ["Rohan takes Tiko to class. Help him sort the puppy, the smart speaker and his dancing robot into Alive or Machine.", "The classroom clock's hands keep moving. Does moving make it alive? Sort it with a sunflower and Moti the puppy.", "A friend's talking toy says “I'm sleepy!” Help Rohan sort it with a tiny seedling and the smart speaker.", "Rohan knows the difference now: living things grow and need care, and machines like Tiko follow programs people write."],
  "teach-pet-machine": ["Rohan is back at Nani’s stall with a fresh pet machine. Help him feed it its first labelled examples: an apple and a rock.", "The machine calls an orange ‘unknown’. Help Rohan add a different fruit, plus a round pebble for the not-fruit side.", "A banana and a toy ball arrive. Help Rohan give the machine a wider set of examples before its last test.", "Nani’s pet machine now learns from varied examples, not one shallow clue, and Rohan still checks every basket."],
  "training-day": ["Tara's club is starting a fresh training set for the finder. Help her label the golden retriever, the indie dog and the backpack correctly.", "The finder just walked past Chikoo the pug. Help Tara find the missing example, and watch out for the toy dog.", "Before the finder goes back on Lane 4, help Tara build a broader test set: an indie puppy, a pug and a toy dog.", "Tara's finder now learns from many kinds of dogs, and her club keeps testing it, because a real finder needs far more varied photos checked by people."],
  "garbage-in-garbage-out": ["Tara is back at the bakery with a new job to fill. Help her check which pretend applicants really have the skills.", "The old helper is still favouring one school name. Help Tara find that unfair feature and switch it off.", "A new baker from School C applies. Help Tara run the fairer rule and check the result herself.", "Tara's helper now compares real skills instead of school names, and Aunt Meera still makes the final choice."],
  "deepfake-detective": ["Kabir is at the media desk. A school-closure clip has no source. Inspect its clues and check the school's notice page before anyone forwards it.", "Now a famous voice seems to praise a miracle app. Help Kabir compare the mouth with the audio, then look for the person's verified channel.", "A friend sends Kabir an urgent edited video. Spot what's off, check an independent source, then choose: share it, or hold and verify?", "Kabir's class group now waits for a known source before sharing a surprising clip. Clues point the way. Sources confirm."],
  "recommendation-rabbit-hole": ["Kabir opens a pretend practice feed to test what he learned. Help him run a safe experiment: tap the school-rules rumour twice and watch the suggestions crowd in.", "Just like his fair feed, Kabir's practice feed is now packed with one topic. Help him follow two different sources to widen it again.", "A new “You will not believe this” clickbait post pops up. Help Kabir keep his balance: follow varied topics and turn on Show fewer clickbait posts.", "Kabir's feed has cricket, science and checked news again, and he knows every click is a signal he gets to choose."],
  "pattern-detective": ["Rohan is back on the trolley, and the screen shows a new gap. Help him find the two-tile group and pick the tile that comes next.", "The next stretch has a trickier rhythm: two the same, then one different. Help Rohan find the repeating group again before the trolley can roll.", "One last gap before Fair Station! Help Rohan finish the three-tile pattern so Nani's trolley can pull in.", "Every gap is fixed. Rohan and Nani roll into the fair on a complete track, and Rohan is a real pattern detective."],
  "step-by-step-morning": ["Rohan is teaching Tikku a brand-new school morning. Help him put Wake up, Brush teeth and Put on shoes in an order that works.", "Next, Tikku packs Rohan's school bag. Help Rohan check the timetable and put the books in before the bag is closed.", "Lunchtime! Help Rohan give Tikku safe steps: wash hands, dry them, then eat.", "Tikku's routines now run in an order that makes sense, and Rohan is ready on time every morning."],
  "flowchart-architect": ["Tara is back at her lab table. Help her pick the right shape for the station's first step: turn on the sensor.", "Now the sensor needs its question. Choose the block that asks 'Hands detected?', then test both paths.", "The hands are rinsed and the wash is done. Help Tara finish her chart with the right shape.", "Tara's station now gives soap when hands are there and waits when they aren't. The judges have their flowchart!"],
  "loop-inspector": ["Dusty is back in the lab with a new list: MOVE RIGHT, written out four times. Help Tara swap it for one loop.", "Mr Rao gives Dusty a bigger job: wash six desks. Help Tara match the repeat count exactly, with no stopping short.", "Before home time, Dusty checks three doors. Help Tara shorten its last program into one neat loop.", "Every program Tara inspected is shorter now, and each loop does exactly the work it should."],
  "complex-algorithmic-logic": ["Kabir is back at the report-card console. Mrs Rao gives him three sample scores: 38, 40 and 74. Help him choose the condition that passes 40 or more, so 38 retries and 40 passes.", "Now the program must check every score in every class, not just one list. Help Kabir pick the nested loops: an outer loop for each class and an inner loop for each score inside it.", "Mrs Rao adds one more rule: distinction for 75 or more. Help Kabir add the second condition, and test 74, 75 and 91 around the new boundary.", "Every sample score now gets the right result, from a retry at 38 to a distinction at 75. Kabir tested every boundary, and Mrs Rao still checks the printout before it goes home."],
  "algorithm-optimization": ["Kabir is back in the sorting lab with a tiny practice list that's already in order. Run both sorts and see which one does less work this time.", "Now Kabir flips the list so the slowest time comes first. Race the sorts on the reversed list and read both counters again.", "Twelve mixed-up relay results arrive at once. Help Kabir find which sort needs fewer comparisons as the list grows.", "Kabir now measures the work, not just the final order. Bubble sort is fine for a tiny, tidy list, but merge sort keeps the big leaderboard fast."],
  "nanis-secret-code": ["Rohan is back at Nani’s house. The parcel caller rings again and asks for her code. Help Rohan shield it and say no.", "The caller hurries them: “The parcel will vanish in one minute!” Help Rohan end the pretend call.", "The phone is quiet again. Help Rohan tell Nani and Mum what happened.", "Nani’s code stayed secret, Mum knows about the call, and Nani and Rohan go back to their carrom game."],
  "surprise-pop-up": ["Rohan is back in his castle game, and another prize window pops up. Help him close it without claiming anything.", "The pop-up comes back and tells Rohan to install a ‘prize helper’. Help him close it and tell Dad.", "Rohan starts a new game, and a ‘bonus gift’ window appears. Show him the same safe habit: close, go back to the game, and report it.", "Rohan’s games are clear of surprise prizes, Mum’s number stayed private, and Dad knows about every pop-up."],
  "otp-guardian": ["Tara is back at Nani’s. A pretend ‘bank officer’ calls again. Help her spot the one thing the caller really wants.", "Now a pretend ‘electricity desk’ threatens to cut the power today. Help Tara and Nani end the call without sharing the OTP.", "The call is over. Help Nani check the problem through the official contact, not the stranger’s number.", "Tara and Nani kept the OTP private and checked with numbers they already trusted. The key code never left Nani’s phone."],
  "qr-code-caution": ["A new buyer messages Tara: “Scan my QR to receive ₹500.” Help her spot what a scan plus a PIN would really do.", "The pretend screen says “Pay ₹500”, and the buyer calls it verification. Help Tara cancel before any PIN is typed.", "Tara’s friend wants to sell old comics too. Help Tara explain the safe way to receive: share your own QR, never enter a PIN.", "Tara reads the money direction on every screen, keeps the UPI PIN for paying only, and lets buyers scan the shop’s own QR."],
  "digital-arrest-simulation": ["A new pretend ‘Cyber Police’ video call pops up in Kabir’s practice lab. Help him inspect it and tap the pressure tactic hiding in the caller’s words.", "The fake officer threatens Kabir’s family and starts a countdown for the fee. Help Kabir end the pretend call instead of paying.", "The call is over, and Papa is right beside him. Help Kabir choose the official way to report it, not the link the caller sent.", "Kabir stayed calm, ended the call, and reported it with his family through official routes: no fee, no secret, and chocolate cake for Dadi."],
  "deepfake-voice-relative-scam": ["Kabir is back at the carrom board when another urgent voice note pings Mum's phone. It sounds just like his uncle, but the number isn't saved. Help Kabir choose the safest first move.", "Now the voice says Uncle Vikram's old number is broken and just trust the voice. Help Kabir find a private family check that goes through a route the family already trusts.", "Kabir can't reach Uncle Vikram yet, and the voice note is still waiting. Help him keep the payment on hold and bring in a trusted adult and another known family contact.", "Kabir knows a familiar voice isn't proof. His family pauses, asks for the passphrase and calls back on saved numbers before anyone sends a rupee."],
};

export function StoryPrelude({ lesson, art, onBegin }: { lesson: CyberLessonMeta; art: string | false; onBegin: () => void }) {
  const story = stories[lesson.slug];
  const [seen, setSeen] = useState<[boolean, boolean]>([false, false]);
  const [latest, setLatest] = useState(-1);
  if (!story) return null;
  const ready = seen.every(Boolean);
  const world = lesson.strand === "Artificial Intelligence" ? "ai" : lesson.strand === "Computational Thinking" ? "logic" : lesson.strand === "Cyber Fraud" ? "fraud" : "security";
  const probe = (index: number) => <button aria-pressed={seen[index]} className={s.probe} data-photo={lesson.slug === "training-day" ? index === 0 ? "golden" : "indie" : lesson.slug === "robot-or-not" && index === 1 ? "indie" : undefined} key={index} onClick={() => { setSeen((current) => current.map((value, i) => i === index ? true : value) as [boolean, boolean]); setLatest(index); }} type="button"><span>{seen[index] ? <ShieldCheck aria-hidden="true" /> : <Eye aria-hidden="true" />}</span>{story.probes[index].label}</button>;
  const sceneResult = latest < 0 ? "Touch the scene to make it respond." : story.probes[latest].reveal;
  return <section className={s.story} data-story={lesson.slug} data-world={world}>
    <div className={s.scene} data-art={art || undefined} data-ready={ready}>
      <div className={s.sceneHeader}><span>{lesson.title}</span><span>Explore the scene</span></div>
      {world === "security" ? <div className={s.securityDevice}><div className={s.deviceBar}><span>CYBERPUR SECURITY</span><i /><i /><i /></div><div className={s.securityDoor}><LockKeyhole aria-hidden="true" /><strong>{story.artifact}</strong><small>{seen.filter(Boolean).length}/2 details checked</small></div><div className={s.deviceReadout} aria-live="polite">{sceneResult}</div><div className={s.probes}>{probe(0)}{probe(1)}</div></div> : null}
      {world === "ai" ? <div className={s.aiMachine}><div className={s.aiTitle}><Bot aria-hidden="true" /><span>{story.artifact}</span></div><div className={s.aiSamples}><span>FEED THE MODEL</span><div className={s.probes}>{probe(0)}{probe(1)}</div></div><div className={s.aiConnector} aria-hidden="true"><span /><ArrowRight /></div><div className={s.aiOutput} aria-live="polite"><strong>{latest < 0 ? "Waiting for examples" : "New evidence noticed"}</strong><p>{sceneResult}</p></div></div> : null}
      {world === "logic" ? <div className={s.routeBoard}><div className={s.routeTitle}><Route aria-hidden="true" /><strong>{story.artifact}</strong></div><div className={s.routeTrack}><span className={s.routeDot}>START</span><span className={s.routeLine} data-lit={seen[0]} /><div className={s.probes}>{probe(0)}{probe(1)}</div><span className={s.routeLine} data-lit={ready} /><span className={s.routeDot}>RESULT</span></div><p className={s.routeOutput} aria-live="polite">{sceneResult}</p></div> : null}
      {world === "fraud" ? <div className={s.callDevice}><div className={s.callBar}><PhoneIncoming aria-hidden="true" /><span>FICTIONAL INCOMING REQUEST</span><i /></div><div className={s.callMessage}><strong>{story.speaker}</strong><p>“{story.line}”</p></div><div className={s.callWarning}><AlertTriangle aria-hidden="true" /><span>{latest < 0 ? "Something about this request feels urgent. Inspect it." : sceneResult}</span></div><div className={s.probes}>{probe(0)}{probe(1)}</div></div> : null}
    </div>
    <div className={s.narrative}><h1>{story.hook}</h1><p className={s.setup}>{story.setup}</p>{world !== "fraud" ? <div className={s.dialogue}><span>{story.speaker}</span><p>“{story.line}”</p></div> : null}{ready ? <div className={s.insight}><strong>What you discovered</strong><p>{story.insight}</p></div> : <p className={s.guide}>Tap both parts of the scene to see what changes.</p>}<div className={s.actions}>{ready ? <button className={s.begin} onClick={onBegin} type="button">Enter the mission <ArrowRight aria-hidden="true" /></button> : null}<button className={s.skip} onClick={onBegin} type="button">Skip story</button></div></div>
  </section>;
}
