"use client";

import { AlertTriangle, ArrowRight, Bot, Eye, LockKeyhole, PhoneIncoming, Route, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { CyberLessonMeta } from "../../../../data/cyber-lessons";
import s from "./story.module.css";

type Probe = { label: string; reveal: string };
type Story = { hook: string; setup: string; speaker: string; line: string; artifact: string; probes: [Probe, Probe]; insight: string };

export const stories: Record<string, Story> = {
  "password-vault-builder": { hook: "The Cyberpur safe clicks shut.", setup: "Moti has tucked the fair tickets inside. A tiny, easy-to-guess key is all that protects them.", speaker: "Moti", line: "Can we make a key I can remember, but a stranger cannot guess quickly?", artifact: "Fair-ticket safe", probes: [{ label: "Try the tiny key", reveal: "A short, familiar key is easy to guess. The safe flashes red." }, { label: "Try a long phrase", reveal: "Several unrelated words make a longer practice key that is easier to remember." }], insight: "A useful password is long and unique. Never type a real password into this game." },
  "sharing-backpack": { hook: "The class noticeboard is open to everyone.", setup: "Nani wants to post a picnic note, but some details would tell strangers too much.", speaker: "Nani", line: "Which things are fine for a class chat, and which need to stay with us?", artifact: "Public picnic board", probes: [{ label: "Pin a favourite colour", reveal: "A favourite colour says little about where someone lives." }, { label: "Pin a home address", reveal: "An address points to a real home. Keep it off a public board." }], insight: "Who can see a post changes what is safe to share. Ask an adult about photos of people." },
  "password-vault": { hook: "One leaked key starts a domino.", setup: "A pretend game account was breached. Its key also opens a school account.", speaker: "Security desk", line: "How far can one stolen key travel?", artifact: "Two connected accounts", probes: [{ label: "Reuse one key", reveal: "The second account becomes exposed when both use the same key." }, { label: "Give each a key", reveal: "A different key keeps the school account out of this leak." }], insight: "Use a different password for every account. Length and uniqueness matter more than tricky symbol rules." },
  "permission-control-panel": { hook: "A flashlight asks to see your contacts.", setup: "The new app also asks for camera and location access before it turns on its light.", speaker: "App request", line: "Allow everything to continue?", artifact: "Permission request", probes: [{ label: "Open contacts access", reveal: "A flashlight does not need the names and numbers in your contacts." }, { label: "Check what light needs", reveal: "The basic light can work without camera, contacts, or location access." }], insight: "Give an app only the access it needs for its actual job." },
  "online-reputation-builder": { hook: "A scholarship team opens a public profile.", setup: "They see a thoughtful project update beside an unkind comment and a class photo posted without asking.", speaker: "Future you", line: "I wish I had looked at what everyone could see.", artifact: "Public profile preview", probes: [{ label: "View the unkind post", reveal: "A public comment can outlast the moment when it felt funny." }, { label: "View the class photo", reveal: "Someone else's image needs their permission before you share it." }], insight: "Pause before posting: consider the audience, the people pictured, and how the post may read later." },
  "email-header-inspector": { hook: "The name says ‘School Office.’ The address doesn't.", setup: "A scholarship email asks for details quickly. The display name looks official, but the hidden address tells another story.", speaker: "Inbox alert", line: "Open the form before midnight to claim your award.", artifact: "Message header", probes: [{ label: "Reveal the From address", reveal: "The real sender domain can differ from the friendly name shown first." }, { label: "Reveal the Reply-To", reveal: "Replies can be routed to yet another address controlled by the sender." }], insight: "A display name is not proof. Inspect the full address and verify through a known school channel." },
  "robot-or-not": { hook: "The dancing robot says hello.", setup: "A puppy barks back. Both move, but only one grows and needs food and care.", speaker: "Cyberpur lab", line: "Does moving and talking make the robot alive?", artifact: "Robot and puppy", probes: [{ label: "Watch the robot", reveal: "Its moves and words follow a program made by people." }, { label: "Watch the puppy", reveal: "The puppy grows, eats, and responds as a living animal." }], insight: "A machine can act lively without being alive. Look for growth and life needs." },
  "teach-pet-machine": { hook: "The pet sorter calls a rock ‘fruit.’", setup: "It saw one round apple and guessed that every round thing belongs in the fruit basket.", speaker: "Pet machine", line: "Round thing found. Fruit?", artifact: "Training tray", probes: [{ label: "Show an apple", reveal: "The machine has seen this kind of fruit before." }, { label: "Show a round rock", reveal: "This example proves shape alone is not enough. The sorter needs more labels." }], insight: "A machine learns from examples. Better, varied examples help it avoid silly guesses." },
  "training-day": { hook: "The dog camera misses a real dog.", setup: "Its training photos mostly show one breed. An indie dog walks into view and the camera hesitates.", speaker: "Camera model", line: "I know the golden retriever. What is this new shape?", artifact: "Dog photo set", probes: [{ label: "Check known photos", reveal: "The model recognizes what its training set included." }, { label: "Check missing breeds", reveal: "Leaving out other dogs makes the model less reliable for them." }], insight: "Test a model on varied examples, especially the kinds it might have missed." },
  "garbage-in-garbage-out": { hook: "Two skilled applicants get different scores.", setup: "A pretend hiring helper copied an old rule that favoured one school name over actual skills.", speaker: "Review team", line: "Their skills match. Why did the tool choose only one?", artifact: "Hiring rule", probes: [{ label: "Compare skills", reveal: "Both applicants meet the same job requirements." }, { label: "Expose school rule", reveal: "The tool uses an unrelated school label. That can create an unfair result." }], insight: "A system can repeat a flawed rule. Check the data and judge people by relevant skills." },
  "deepfake-detective": { hook: "A shocking school clip arrives without a source.", setup: "The video claims school closes tomorrow. It looks polished enough to spread quickly.", speaker: "Class group", line: "Should we forward it now?", artifact: "Unverified clip", probes: [{ label: "Inspect the clip", reveal: "Odd audio or visuals can be clues, but they do not prove a clip is fake." }, { label: "Check school source", reveal: "A known school channel can confirm or contradict the claim independently." }], insight: "Hold the share button. Check an independent source before trusting a surprising clip." },
  "recommendation-rabbit-hole": { hook: "One wild clip changes the whole feed.", setup: "The app notices every pause and click. Soon similar posts crowd out other topics.", speaker: "Feed engine", line: "You watched that one. Want twelve more?", artifact: "Suggestion feed", probes: [{ label: "Replay the rumour", reveal: "Repeated attention tells the feed to show more of the same topic." }, { label: "Seek another topic", reveal: "Following varied topics gives the feed a wider signal." }], insight: "Recommendations react to behaviour. Choose varied sources instead of letting one click choose for you." },
  "pattern-detective": { hook: "Nani's trolley stops at a missing tile.", setup: "The station track has a rhythm. A new tile must match the repeating group before the trolley can roll.", speaker: "Nani", line: "Can you spot what the track is trying to repeat?", artifact: "Trolley track", probes: [{ label: "Trace the first group", reveal: "Look for the smallest group of shapes that repeats." }, { label: "Trace the next group", reveal: "The same order appears again. The missing tile continues it." }], insight: "A pattern is a repeated rule. Find the group, then predict what comes next." },
  "step-by-step-morning": { hook: "The morning robot puts on shoes before socks.", setup: "It followed the steps exactly as written. Now it is stuck at the door.", speaker: "Morning robot", line: "Instruction complete. Why is this uncomfortable?", artifact: "Routine cards", probes: [{ label: "Run the bad order", reveal: "A computer follows a sequence even when the result makes no sense." }, { label: "Move the first step", reveal: "Putting actions in a useful order changes the outcome." }], insight: "A sequence is an ordered set of steps. Change the order, and you change the result." },
  "flowchart-architect": { hook: "The wash station sprays an empty sink.", setup: "Its plan skips the question ‘Are hands here?’ and dispenses soap every time.", speaker: "Workshop team", line: "We need the station to decide before it acts.", artifact: "Sensor path", probes: [{ label: "Test: hands present", reveal: "A YES path can dispense soap and continue washing." }, { label: "Test: no hands", reveal: "A NO path should wait. The decision diamond separates the two outcomes." }], insight: "A flowchart shows actions and decisions. Test both sides of a question." },
  "loop-inspector": { hook: "The cleaner's program repeats itself four times.", setup: "Four identical commands fill the screen. The robot can do the same work with a shorter instruction.", speaker: "Robot cleaner", line: "MOVE RIGHT. MOVE RIGHT. MOVE RIGHT. MOVE RIGHT.", artifact: "Robot command strip", probes: [{ label: "Run the long list", reveal: "The robot moves four steps, one command at a time." }, { label: "Run REPEAT 4", reveal: "One loop runs the same command four times with less code." }], insight: "A loop repeats an action. The repeat count must match the work you want done." },
  "complex-algorithmic-logic": { hook: "A score of exactly 40 gets the wrong result.", setup: "The grade processor says ‘retry’ even though 40 should pass. One symbol in the rule is missing.", speaker: "Test console", line: "38: retry · 40: retry · 74: pass", artifact: "Boundary test", probes: [{ label: "Test score 39", reveal: "39 should retry, so the rule must still reject scores below 40." }, { label: "Test score 40", reveal: "40 should pass. The rule needs ≥ rather than >." }], insight: "Test the boundary value. A tiny condition change can change someone's outcome." },
  "algorithm-optimization": { hook: "Two sorters finish with the same order.", setup: "One makes many comparisons; the other groups its work. The winner changes with the size and order of the list.", speaker: "Sorting lab", line: "Same answer. Did they do the same amount of work?", artifact: "Comparison race", probes: [{ label: "Try a small sorted list", reveal: "Bubble sort can stop early when nothing needs swapping." }, { label: "Try a larger mixed list", reveal: "Merge sort usually uses fewer comparisons as mixed lists grow." }], insight: "Correct output is only part of the story. Measure the work an algorithm does." },
  "nanis-secret-code": { hook: "A stranger calls about Nani's parcel.", setup: "They sound helpful, but they ask for the one-time code that just appeared on her phone.", speaker: "Unknown caller", line: "Read me the six digits. The parcel is waiting.", artifact: "Incoming call", probes: [{ label: "Look at the code", reveal: "The code is a temporary key. Sharing it gives someone else power to act." }, { label: "Look at the caller", reveal: "A friendly voice is not proof of identity. The request is the warning sign." }], insight: "Keep one-time codes private. End the call and tell Nani or another trusted adult." },
  "surprise-pop-up": { hook: "A prize window covers the game.", setup: "Nobody entered a contest, but the screen says a free tablet is waiting behind a big claim button.", speaker: "Pop-up", line: "Claim your prize before the timer ends!", artifact: "Game overlay", probes: [{ label: "Inspect the claim button", reveal: "A surprise offer tries to pull you away from the game." }, { label: "Find the close control", reveal: "Closing the overlay clears the game without following its instructions." }], insight: "Unexpected prize windows are easy to close. Do not enter codes or install their helpers." },
  "otp-guardian": { hook: "A ‘bank officer’ asks for an OTP.", setup: "The caller says the card is frozen and the secret code will fix it immediately.", speaker: "Unknown number", line: "Tell me the OTP now or your account will stop working.", artifact: "Pressure call", probes: [{ label: "Inspect the title", reveal: "A caller can claim to be bank staff. The title itself proves nothing." }, { label: "Inspect the request", reveal: "The caller wants an OTP. That is the risky action, whatever their title." }], insight: "Never give an OTP to a caller. Use a known official channel if you need to check an issue." },
  "qr-code-caution": { hook: "The buyer says ‘receive ₹500.’ The phone says ‘Pay ₹500.’", setup: "A QR scan has opened a pretend payment screen. The two descriptions point in opposite directions.", speaker: "Buyer", line: "Enter your PIN. It is just verification.", artifact: "Payment direction", probes: [{ label: "Read the Pay label", reveal: "The screen shows money leaving your account, not arriving." }, { label: "Inspect the PIN request", reveal: "A UPI PIN authorizes a payment. It is not needed to receive money." }], insight: "Read the payment direction yourself. Cancel a debit you did not mean to make." },
  "digital-arrest-simulation": { hook: "A fake officer orders you to stay on the call.", setup: "They demand secrecy and a fee while claiming you are under ‘digital arrest.’", speaker: "Unknown video caller", line: "Do not tell anyone. Pay now or your family is in trouble.", artifact: "Intimidation call", probes: [{ label: "Inspect the secrecy demand", reveal: "Isolation makes it harder to ask a trusted person for help." }, { label: "Inspect the fee demand", reveal: "The urgent payment demand is another warning sign of this scam." }], insight: "End the call, tell a trusted adult, and use an official reporting channel in India." },
  "deepfake-voice-relative-scam": { hook: "An urgent voice note sounds like your uncle.", setup: "The number is unknown. The voice asks for money and says not to call anyone else.", speaker: "Voice note", line: "It is me. Send money quickly. My old phone is broken.", artifact: "Unknown voice note", probes: [{ label: "Listen to the voice", reveal: "A familiar sound can be imitated. Voice alone is not identity proof." }, { label: "Check the number", reveal: "The request came from an unknown route. Call a saved number or another known contact." }], insight: "Pause the payment until you verify through a contact route you already trust." },
};

/** Scene direction for the three practice turns, followed by the story payoff. */
export const storyArcs: Record<string, [string, string, string, string]> = {
  "password-vault-builder": ["Rohan is back in his game. Help him practise a long secret in this pretend password vault.", "A friend used Password123. Help Rohan show them a less predictable practice phrase.", "Rohan needs a different secret for his school account. Build a new phrase for its vault.", "Rohan knows how to build longer secrets, use a different one for each account, and ask a trusted adult for help."],
  "sharing-backpack": ["Nani is filling the public picnic board. Sort what can be shown.", "A second class post includes contact details and a friend's photo.", "Pack one final set before the board goes live.", "The class board shares the fun without exposing private details."],
  "password-vault": ["Give the first account a key that will not be easily guessed.", "A second account needs its own key, not a copy.", "The game account leaks. See whether the school account falls too.", "The school account stayed safe because its key was different."],
  "permission-control-panel": ["A flashlight app is at the permission gate.", "A new app has a different job. Review its requests on their own merits.", "One more request tests whether you can keep access minimal.", "The apps can do their jobs without collecting access they do not need."],
  "online-reputation-builder": ["The scholarship team is scrolling the public profile.", "A team update needs a kinder, clearer version before posting.", "Publish a fresh example that respects the people involved.", "The public profile now shows care, consent, and useful work."],
  "email-header-inspector": ["The first scholarship message looks official at a glance.", "A second message hides another address behind its reply route.", "One final sender tries to borrow the school's identity.", "You checked where the messages really came from before trusting them."],
  "robot-or-not": ["The Cyberpur parade mixes animals with talking machines.", "A new set moves in. Look beyond whether it can move or speak.", "Sort the last arrivals by what makes something alive.", "The parade now separates living things from programmed machines."],
  "teach-pet-machine": ["Feed the pet machine its first labeled examples.", "The next tray contains a new kind of fruit and a new round object.", "Give the machine a wider set before its last test.", "The pet machine learned from better examples instead of one shallow clue."],
  "training-day": ["The dog camera needs labels beyond one familiar breed.", "A new set arrives with a breed it has not seen enough.", "Repair the final training tray and test again.", "The recognizer now has a broader practice set, though a real model needs far more review."],
  "garbage-in-garbage-out": ["The review team checks who has the right skills.", "The copied school rule is still hiding in the helper.", "Remove the irrelevant rule and rerun a fresh case.", "The pretend hiring helper now compares relevant skills instead of school labels."],
  "deepfake-detective": ["A school-closure clip is about to be forwarded.", "A second clip makes a different claim. Inspect and corroborate it.", "One last surprise tests your share-or-verify habit.", "The class group paused the rumours until a known source could confirm them."],
  "recommendation-rabbit-hole": ["Watch how repeated clicks reshape the suggestions.", "Widen the feed by choosing more than one topic.", "Keep the balance when another tempting rumour appears.", "You nudged the feed toward a wider mix of topics and sources."],
  "pattern-detective": ["Nani's trolley waits at the first gap in the track.", "A new rhythm appears. Find the repeating group again.", "The last missing tile is the final stop before the station.", "Nani's trolley has a complete track to the station."],
  "step-by-step-morning": ["The morning robot needs a useful school-day order.", "A packed bag must be prepared before it can be closed.", "The lunch routine tests whether the robot can follow safe steps.", "The robot's routines now run in an order that makes sense."],
  "flowchart-architect": ["The wash station needs its first action block.", "Now give the sensor a decision point and test both paths.", "Finish the route after the hands are washed.", "The station now acts when hands are present and waits when they are not."],
  "loop-inspector": ["The cleaner has four identical commands to compress.", "The next job repeats more times. Match the count exactly.", "A final route checks whether you can write a shorter program.", "The cleaner did the same work with shorter instructions."],
  "complex-algorithmic-logic": ["The score processor fails at the pass boundary.", "Several classes must be checked, one score at a time.", "A distinction rule adds one more boundary to test.", "The processor now handles the sample boundary cases correctly."],
  "algorithm-optimization": ["Race the two sorters on a list that is already neat.", "Reverse the list and compare the work again.", "A larger mixed list reveals how the methods scale.", "You compared measured work instead of guessing from the final order."],
  "nanis-secret-code": ["Nani's parcel caller asks for the secret code.", "The caller raises the pressure. Stop the pretend call.", "The phone is quiet. Bring Nani and a trusted adult into the story.", "Nani's code stayed private, and a trusted adult knows what happened."],
  "surprise-pop-up": ["A prize overlay blocks the game. Clear it safely.", "The pop-up returns with an install demand.", "A new game tries the same trick. Use the habit again.", "The games are clear of surprise offers, and an adult has been told."],
  "otp-guardian": ["The caller's title sounds official. Inspect what they actually request.", "A new caller adds a threat and a deadline.", "The call is over. Check any real issue through a known route.", "The OTP stayed private while the account issue was checked independently."],
  "qr-code-caution": ["The buyer's words and the payment screen disagree.", "The phone shows a debit. Stop it before a PIN is entered.", "Show a friend the safe way to receive by QR.", "You read the money direction and kept the UPI PIN out of a fake receipt."],
  "digital-arrest-simulation": ["The fake officer tries to isolate you on a video call.", "The threats grow louder. End the pretend call.", "Now choose a real reporting route with a trusted adult.", "The pressure call ended, and the report went through an official route."],
  "deepfake-voice-relative-scam": ["The urgent voice note sounds familiar, but the number is not.", "The caller says the saved number is broken. Verify another way.", "No one has confirmed the request. Keep the payment on hold.", "The family checked through known contacts before anyone sent money."],
};

export function StoryPrelude({ lesson, art, onBegin }: { lesson: CyberLessonMeta; art: string | false; onBegin: () => void }) {
  const story = stories[lesson.slug];
  const [seen, setSeen] = useState<[boolean, boolean]>([false, false]);
  const [latest, setLatest] = useState(-1);
  if (!story) return null;
  const ready = seen.every(Boolean);
  const world = lesson.strand === "Artificial Intelligence" ? "ai" : lesson.strand === "Computational Thinking" ? "logic" : lesson.strand === "Cyber Fraud" ? "fraud" : "security";
  const probe = (index: number) => <button aria-pressed={seen[index]} className={s.probe} data-photo={lesson.slug === "training-day" ? index === 0 ? "golden" : "indie" : lesson.slug === "robot-or-not" && index === 1 ? "indie" : undefined} key={index} onClick={() => { setSeen((current) => current.map((value, i) => i === index ? true : value) as [boolean, boolean]); setLatest(index); }} type="button"><span>{seen[index] ? <ShieldCheck aria-hidden="true" /> : <Eye aria-hidden="true" />}</span>{story.probes[index].label}</button>;
  const sceneResult = latest < 0 ? "Touch the scene to make it respond." : story.probes[latest].reveal;
  return <section className={s.story} data-story={lesson.slug} data-world={world}>
    <div className={s.scene} data-art={art || undefined} data-ready={ready}>
      <div className={s.sceneHeader}><span>{lesson.title}</span><span>Explore the scene</span></div>
      {world === "security" ? <div className={s.securityDevice}><div className={s.deviceBar}><span>CYBERPUR SECURITY</span><i /><i /><i /></div><div className={s.securityDoor}><LockKeyhole aria-hidden="true" /><strong>{story.artifact}</strong><small>{seen.filter(Boolean).length}/2 details checked</small></div><div className={s.deviceReadout} aria-live="polite">{sceneResult}</div><div className={s.probes}>{probe(0)}{probe(1)}</div></div> : null}
      {world === "ai" ? <div className={s.aiMachine}><div className={s.aiTitle}><Bot aria-hidden="true" /><span>{story.artifact}</span></div><div className={s.aiSamples}><span>FEED THE MODEL</span><div className={s.probes}>{probe(0)}{probe(1)}</div></div><div className={s.aiConnector} aria-hidden="true"><span /><ArrowRight /></div><div className={s.aiOutput} aria-live="polite"><strong>{latest < 0 ? "Waiting for examples" : "New evidence noticed"}</strong><p>{sceneResult}</p></div></div> : null}
      {world === "logic" ? <div className={s.routeBoard}><div className={s.routeTitle}><Route aria-hidden="true" /><strong>{story.artifact}</strong></div><div className={s.routeTrack}><span className={s.routeDot}>START</span><span className={s.routeLine} data-lit={seen[0]} /><div className={s.probes}>{probe(0)}{probe(1)}</div><span className={s.routeLine} data-lit={ready} /><span className={s.routeDot}>RESULT</span></div><p className={s.routeOutput} aria-live="polite">{sceneResult}</p></div> : null}
      {world === "fraud" ? <div className={s.callDevice}><div className={s.callBar}><PhoneIncoming aria-hidden="true" /><span>FICTIONAL INCOMING REQUEST</span><i /></div><div className={s.callMessage}><strong>{story.speaker}</strong><p>“{story.line}”</p></div><div className={s.callWarning}><AlertTriangle aria-hidden="true" /><span>{latest < 0 ? "Something about this request feels urgent. Inspect it." : sceneResult}</span></div><div className={s.probes}>{probe(0)}{probe(1)}</div></div> : null}
    </div>
    <div className={s.narrative}><h1>{story.hook}</h1><p className={s.setup}>{story.setup}</p>{world !== "fraud" ? <div className={s.dialogue}><span>{story.speaker}</span><p>“{story.line}”</p></div> : null}{ready ? <div className={s.insight}><strong>What you discovered</strong><p>{story.insight}</p></div> : <p className={s.guide}>Tap both parts of the scene to see what changes.</p>}<div className={s.actions}>{ready ? <button className={s.begin} onClick={onBegin} type="button">Enter the mission <ArrowRight aria-hidden="true" /></button> : null}<button className={s.skip} onClick={onBegin} type="button">Skip story</button></div></div>
  </section>;
}
